[tool.pinto]
# note: until pinto update gets in, any steps
# that have subcommands will fail (e.g. training and sampling)
steps = [
    "data_generation:generate-background",
    "data_generation:generate-waveforms",
    "data_generation:generate-flow-injections",
    "data_generation:generate-bilby-injections",
    "sample_with_bilby:sample-with-bilby",
    "train:train:maf",
    "sample_with_flow:sample-with-flow:maf"
]

[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
ifos = ['H1', 'L1']
# note: due to how ml4gw returns extrinsic parameters, the ordering of dec, psi, phi is important,
# and these parameters should be at the end. We should find a way to make this more robust.
inference_params = ["frequency", "quality", "hrss", "phase", "dec", "psi", "phi"]
trigger_distance = 0.0
start = 1262044818
stop = 1262088018
test_stop = 1262100018
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
frame_type = "HOFT_C01"
prior = "mlpe.injection.priors.sg_uniform"
state_flag = "DCS-ANALYSIS_READY_C01:1"
repository_directory = "${BASE_DIR}/model_repo/" 
force_generation = false
kernel_length = 2
highpass = 32
fduration = 1
waveform_duration = 8
bilby_duration = 4

# training parameters
batches_per_epoch = 300
max_epochs = 500

# flow subcommands
coupling = {num_flow_steps = 10}
maf = {num_transforms = 6, num_blocks = 2, use_batch_norm = true}

# embedding subcommands
dense = {context_dim = 50, hidden_layer_size = 128, num_hidden_layers = 2}
coherent = {context_dim = 50, hidden_layer_size = 128, num_hidden_layers = 2}
resnet = {context_dim = 50, layers = [2, 2], norm_groups = 8}

[tool.typeo.scripts.generate-background]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
start = "${base.start}" 
stop = "${base.stop}" 
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}" 
minimum_length = 10000
force_generation = "${base.force_generation}"
df = 0.125
gaussian = true

[tool.typeo.scripts.generate-waveforms]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
n_samples = 100000
sample_rate = "${base.sample_rate}" 
force_generation = "${base.force_generation}"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"
waveform_duration = "${base.waveform_duration}"
prior = "${base.prior}"

[tool.typeo.scripts.train]
waveform_dataset = "${base.datadir}/signals.h5"
background_path = "${base.datadir}/background.h5" 
logdir = "${base.logdir}"
outdir = "${base.basedir}/training"
inference_params = "${base.inference_params}"

ifos = "${base.ifos}"
kernel_length = "${base.kernel_length}"
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
highpass = 32 
trigger_distance = "${base.trigger_distance}"
batch_size = 512
batches_per_epoch = "${base.batches_per_epoch}"
max_epochs = "${base.max_epochs}"

early_stop = 150

use_amp = true
profile = true
device = "cuda"
profile = false
valid_frac = 0.25
valid_stride = 0.0625

# flow subcommand
[tool.typeo.scripts.train.flow]
coupling = "${base.coupling}"
maf = "${base.maf}"

# embedding subcommand
[tool.typeo.scripts.train.embedding]
dense = "${base.dense}"
coherent = "${base.coherent}"
resnet = "${base.resnet}"

# scheduler subcommand
[tool.typeo.scripts.train.optimizer]
adam = {lr = 1e-4, weight_decay = 1e-4}

# optimizer subcommand
[tool.typeo.scripts.train.scheduler]
onecycle = {max_lr = 5e-3, epochs = "${base.max_epochs}", lr_ramp_epochs = 100, steps_per_epoch = "${base.batches_per_epoch}" }


[tool.typeo.scripts.generate-flow-injections]
ifos = "${base.ifos}"
state_flag = "${base.state_flag}"
frame_type = "${base.frame_type}"
channel = "${base.channel}"
start = "${base.stop}"
stop = "${base.test_stop}" 
sample_rate = "${base.sample_rate}"
prior = "${base.prior}"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"
n_samples = 1000
kernel_length = "${base.kernel_length}"
waveform_duration = "${base.waveform_duration}"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
gaussian = false

[tool.typeo.scripts.generate-bilby-injections]
bilby_duration = "${base.bilby_duration}"
ifos = "${base.ifos}"
state_flag = "${base.state_flag}"
frame_type = "${base.frame_type}"
channel = "${base.channel}"
start = "${base.stop}"
stop = "${base.test_stop}"
sample_rate = "${base.sample_rate}"
prior = "mlpe.injection.priors.sg_uniform"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"
n_samples = 8
waveform_duration = "${base.waveform_duration}"
spacing = 100
buffer = 10
datadir = "${base.datadir}"
logdir = "${base.logdir}"
gaussian = false

[tool.typeo.scripts.sample-with-bilby]
request_cpus = 24
n_live = 256
n_act = 5
ifos = "${base.ifos}"
bilby_duration = "${base.bilby_duration}"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
accounting_group = "${LIGO_ACCOUNTING_GROUP}"
channel = "${base.channel}"
sample_rate = "${base.sample_rate}"
prior = "${base.prior}"
force_generation = false

[tool.typeo.scripts.sample-with-flow]
ifos = "${base.ifos}"
kernel_length = "${base.kernel_length}"
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
model_state_path = "${base.basedir}/training/weights.pt"
inference_params = "${base.inference_params}"
basedir = "${base.basedir}"
datadir = "${base.datadir}"
num_samples_draw = 10000
device = "cuda"

# flow subcommand
[tool.typeo.scripts.sample-with-flow.flow]
maf = "${base.maf}"
coupling = "${base.coupling}"

# embedding subcommand
[tool.typeo.scripts.sample-with-flow.embedding]
dense = "${base.dense}"
coherent = "${base.coherent}"
resnet = "${base.resnet}"
