[tool.pinto]
steps = [
    "generate_background:generate-background",
    "generate_waveforms:generate-waveforms",
    "generate_testing_set:generate-testing",
    "train:train:coupling"
]


[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
ifos = ['H1', 'L1']
start = 1262607622
stop = 1262620622
test_stop = 1262751694
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
frame_type = "HOFT_C01"
state_flag = "DCS-ANALYSIS_READY_C01:1"
repository_directory = "${BASE_DIR}/model_repo/" 
force_generation = false
kernel_length = 2
highpass = 32
fduration = 1
waveform_duration = 8
prior_file = "priors/sine_gaussian.prior"
coupling = {num_flow_steps = 10}


[tool.typeo.scripts.generate-background]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
start = "${base.start}" 
stop = "${base.stop}" 
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}" 
minimum_length = 10000
force_generation = "${base.force_generation}"

[tool.typeo.scripts.generate-waveforms]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
n_samples = 10000
prior_file = "${base.prior_file}"
sample_rate = "${base.sample_rate}" 
force_generation = "${base.force_generation}"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"
waveform_duration = "${base.waveform_duration}"


[tool.typeo.scripts.train]
waveform_dataset = "${base.datadir}/signals.h5"
background_path = "${base.datadir}/background.h5" 
logdir = "${base.logdir}"
outdir = "${base.basedir}/training"
inference_params = ["frequency", "quality", "hrss", "dec", "psi", "phi"]

ifos = "${base.ifos}"

kernel_length = "${base.kernel_length}"
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
highpass = 32 
trigger_distance = 0.0
batch_size = 512
batches_per_epoch = 200
max_epochs = 300

lr = 4e-3
min_lr = 1e-5
decay_steps = 10000
weight_decay = 1e-5
early_stop = 50

device = "cuda"
profile = false
use_amp = false
valid_frac = 0.25
valid_stride = 0.0625

# arch parameters
commands.coupling = "${base.coupling}"


[tool.typeo.scripts.generate-testing]
ifos = "${base.ifos}"
state_flag = "${base.state_flag}"
frame_type = "${base.frame_type}"
channel = "${base.channel}"
start = "${base.stop}"
stop = "${base.test_stop}" 
sample_rate = "${base.sample_rate}"
prior = "mlpe.injection.priors.sg_uniform"
waveform = "mlpe.injection.waveforms.sine_gaussian_frequency"
n_samples = 1000
kernel_length = "${base.kernel_length}"
waveform_duration = "${base.waveform_duration}"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
